baseurl = "https://ricettedimaria.netlify.app/"
languageCode = "it-it"
theme = "hugo-theme-stack"
paginate = 5
title = "Ricette di Maria"
disqusShortname = "ricettedimaria"
DefaultContentLanguage = "it"

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = "🌸"
  subtitle = "Vuoi cucinare qualcosa? Sei nel posto giusto!"

    [params.sidebar.avatar]
    local = true
    src = "../../img/avatar1.png"

  [params.article]
  math = false

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "disqus"

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]

  [params.widgets]
  enabled = [ "search", "archives", "tag-cloud" ]

    [params.widgets.archives]
    limit = 5

    [params.widgets.tagCloud]
    limit = 10

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "light"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tag"
  weight = 100

  [[related.indices]]
  name = "categorie"
  weight = 200

[markup.highlight]
noClasses = false

